# Generated by Django 4.2.5 on 2023-09-17 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IP_results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=200)),
                ('IP_address', models.GenericIPAddressField()),
                ('ip_state', models.CharField(max_length=20)),
            ],
        ),
    ]
