# Generated by Django 4.2.5 on 2023-09-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0004_cidr_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidr_table',
            name='cidr',
            field=models.CharField(max_length=3),
        ),
    ]
